name: Pre-Release Actions

on: 
  workflow_dispatch:

jobs:

  version-bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

